export const occupationData = [
  "Business Domain",
  "Agriculture",
  "Automotive",
  "Banking",
  "Consulting",
  "Distribution",
  "Exhibition/Events",
  "Financial Services",
  "Industrial",
  "Law Firm",
  "Luxury Goods",
  "Manufacturing",
  "Media",
  "Pharma",
  "Public Sector",
  "Real State",
  "Research",
  "Technology",
  "Other",
];
