const EmpDetails = [
  {
    name: "Md Sibgatullah Amir",
    phNum: "7970942455",
    email: "amir@placementplaza.com",
    companyId: "2022CTO344",
    post: "Chief Technical Officer",
    qualifications:
      "Bachelor Of Technology In Computer Science & Engineering from Accurate Institute Of Management & Technology",
    img: "/EmpDetails/amir.jpeg",
  },
  {
    name: "Mo. Kaif Siddique",
    phNum: "9119967505",
    email: "kaifsid774@gmail.com",
    companyId: "2024ITSP004",
    post: "IT Support Specialist [Intern]",
    qualifications: "Have done Bachelor's in Technology, Stream - ECE",
    img: "/EmpDetails/whiteKaif.png",
  },
  {
    name: "Komal Sharma",
    phNum: "7827939904",
    email: "komalsharmasharda@gmail.com",
    companyId: "2024MGTPR03",
    post: "Administrative Assistant  [Intern]",
    qualifications:
      "Have done Bachelor's of Buisness Admistration, Stream - Banking and Finance ",
    img: "/EmpDetails/komal.png",
  },
  {
    name: "Riya Prasad",
    phNum: "9354107654",
    email: "itsofficialriya142@gmail.com",
    companyId: "2024AO981",
    post: "PR Head and Designing/Administrative Officer  [Intern]",
    qualifications:
      "Pursuing Bachelor's in Computer Science Engineering, Stream - AI/ML",
    img: "/EmpDetails/riya.png",
  },
  {
    name: "Saima Rahman",
    phNum: "8595838269",
    email: "rahmansaima620@gmail.com",
    companyId: "2022HRH601",
    post: "HR Head  [Intern]",
    qualifications: "Pursuing BBA IIIrd year",
    img: "/EmpDetails/saima.png",
  },
  {
    name: "Rishabh Singh",
    phNum: "9354728835",
    email: "rishabsingh336@gmail.com",
    companyId: "2024SME004",
    post: "HR [Intern]",
    qualifications: "Pursuing BBA IIIrd year",
    img: "/EmpDetails/risabh.png",
  },
  {
    name: "Bushra Jawwad",
    phNum: "8700040345",
    email: "khanbushra87000@gmail.com",
    companyId: "2022JMC955",
    post: "Junior Managing Coordinator [Intern]",
    qualifications: "Pursuing BBA in Healthcare Management",
    img: "/EmpDetails/bushra.png",
  },
  {
    name: "Krish Rai",
    phNum: "9999356058",
    email: "krishrai192004@gmail.com",
    companyId: "2024OM332",
    post: "Operation Manager [Intern]",
    qualifications: "Pursuing BBA in Banking and Finance",
    img: "/EmpDetails/krish.png",
  },
  {
    name: "Mohd Aquib",
    phNum: "7017493431",
    email: "mohdaqib921@gmail.com",
    companyId: "2024FSD345",
    qualifications: "Have done Bachelor's in Technology, Stream - ECE",
    img: "/EmpDetails/aqib.jpeg",
  },
  {
    name: "Shaniya Jamal",
    phNum: "+91 78270 87389",
    email: "shaniyajamalppz006@gmail.com",
    companyId: "PPZ006",
    post: "Industrial relation head",
    qualifications: "MBA HR & marketing",
    img: "/EmpDetails/shaniya.jpeg",
  },
];

export default EmpDetails;
